




.build/atmega328/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/atmega328/src
	@echo [93msrc/sketch.ino[0m
	@/Users/million/.pyenv/versions/2.7.6/bin/ino preproc  -o $@ $^


all : .build/atmega328/src/sketch.cpp
	@true

